export enum Route {
  RootStack = 'RootStack',
  SplashScreen = 'Splash',
  OnboardingScreen = 'Onboarding',
  AuthStack = 'AuthStack',
  PhoneVerificationStack = 'PhoneVerificationStack',
  LoginScreen = 'Login',
  SignUpScreen = 'SignUp',
  AccountSetUpScreen = 'AccountSetUp',
  PhoneNumberVerificationScreen = 'PhoneNumberVerification',
  PhoneNumberInputScreen = 'PhoneNumberInput',
  LocationScreen = 'Location',
  AddressScreen = 'Address',
  ResetPasswordScreen = 'ResetPassword',
  BottomStack = 'BottomStack',
  AccountStack = 'AccountStack',
  AccountAddressScreen = 'AccountAddress',
  AddressEditScreen = 'AddressEdit',
  AccountScreen = 'Account',
  MyDetailsScreen = 'MyDetails',
  ChangePasswordScreen = 'ChangePassword',
  BasketStack = 'BasketStack',
  BasketScreen = 'Basket',
  BrowseStack = 'BrowseStack',
  BrowseScreen = 'Browse',

  MainStack = 'MainStack',
  HomeScreen = 'Home',
}
